name: google_books_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.4
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0-dev.11
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  hooks_riverpod: ^1.0.0-dev.11
  http: ^0.13.4
  json_serializable: ^5.0.2
  lint: ^1.7.2
  logger: ^1.1.0
  shared_preferences: ^2.0.8
  state_notifier: ^0.7.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/book.png
    - assets/nocover.png
    - assets/no_cover.gif
    - assets/searching.png
    - assets/Home.png
    - assets/Search.png
    - assets/Star.png

